### ISSUE TITLE
NameError: name 'rsutilwrapper' is not defined

### ISSUE THREAD

**Issue by kazoo-kmt** [toinsson/pyrealsense#12]
It looks `rsutilwrapper` is not defined if it doesn't go into if sentence.
https://github.com/toinsson/pyrealsense/blob/master/pyrealsense/__init__.py#L22

**Comment by kazoo-kmt** [comment]
It's better to add `if 'rsutilwrapper' in locals():` before L22?

**Comment by toinsson** [comment]
I am guessing on Mac Os ?

Please provide more info about your machine platform, camera model and librealsense version.

**Comment by kazoo-kmt** [comment]
I'm using Ubuntu 16.04 LTS (on mac's VirtualBox VM 5.0.30), SR300 and the latest librealsense version 1.12.1 for this issue.

**Comment by toinsson** [comment]
please check latest
