### ISSUE TITLE
access to extrinsics

### ISSUE THREAD

**Issue by nwestbury** [toinsson/pyrealsense#14]
| Required Info  |   |
|---|---|
| Camera Model | SR300 | 
| Firmware Version | 3.10.10.0 | 
| Operating System & Version | Ubuntu 16.04.1 LTS |

Silly question. How do I access `rs_get_device_extrinsics` from the [librealsense C API](https://github.com/IntelRealSense/librealsense/blob/master/include/librealsense/rs.h)? It seems like this was directly possible [at one point](https://github.com/toinsson/pyrealsense/commit/0d298642d382167515e5ca20194bc6e016982f52). Thanks for making this nifty wrapper!

**Comment by toinsson** [comment]
Indeed. It's been removed .. I'll put that back in the next release, should be this week hopefully.

**Comment by toinsson** [comment]
you should have a look at latest:

    def get_device_extrinsics(self, from_stream, to_stream):
        """Retrieve extrinsic transformation between the viewpoints of two different streams."""
        _rs_extrinsics = rs_extrinsics()
        lrs.rs_get_device_extrinsics(
            self.dev,
            from_stream,
            to_stream,
            ctypes.byref(_rs_extrinsics),
            ctypes.byref(e))
        _check_error(e)
        return _rs_extrinsics

This should do the trick. 

    e = dev.get_device_extrinsics(pyrs.rs_stream.RS_STREAM_COLOR, pyrs.rs_stream.RS_STREAM_DEPTH)

**Comment by nwestbury** [comment]
Yeah that works. Thanks!

**Comment by toinsson** [comment]
by the way, 
not all librealsense functionality is wrapped in pyrealsense. But for most part it would be trivial to add a method on the DeviceBase class.
On top of that, you can also make direct call through `pyrs.lrs`.
