### ISSUE TITLE
can't install the libreary

### ISSUE THREAD

**Issue by helxsz** [toinsson/pyrealsense#2]
when I tried to install the libreary, I got a error compiling message, as shown below. My linux is 14.04, my numpy version is 1.8.2

running install
running build
running build_ext
building 'pyrealsense' extension
creating build
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/src
arm-linux-gnueabihf-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/librealsense -I/usr/include/python2.7 -c src/realsense.c -o build/temp.linux-armv7l-2.7/src/realsense.o
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/realsense.c:8:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
src/realsense.c: In function ‘apply_ivcam_preset’:
src/realsense.c:544:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i=0; i<15; i++)
     ^
src/realsense.c:544:5: note: use option -std=c99 or -std=gnu99 to compile your code
In file included from src/realsense.c:11:0:
src/realsense.c: At top level:
/usr/local/include/librealsense/rsutil.h:61:13: warning: ‘rs_apply_depth_control_preset’ defined but not used [-Wunused-function]
 static void rs_apply_depth_control_preset(rs_device * device, int preset)
             ^
/usr/local/include/librealsense/rsutil.h:87:13: warning: ‘rs_apply_ivcam_preset’ defined but not used [-Wunused-function]
 static void rs_apply_ivcam_preset(rs_device * device, int preset)
             ^
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**Comment by toinsson** [comment]
**src/realsense.c:544:5: error: ‘for’ loop initial declarations are only allowed in C99 mode** is the issue. 

Depends on your version of `gcc` I guess.

You can change the source code to take the loop variable declaration out, for [example](http://stackoverflow.com/questions/24881/how-do-i-fix-for-loop-initial-declaration-used-outside-c99-mode-gcc-error).
