### ISSUE TITLE
Memory leak: application memory grows continuously

### ISSUE THREAD

**Issue by massimilianoC** [toinsson/pyrealsense#22]
Hi, i'm trying to optimize my code, but application memory grows at each cycle. Is there any function or way to optimize memory?
Thanks

| Info  |   |
|---|---|
| Camera Model | R200 | 
| Firmware Version | 1.0.71.06  | 
| Operating System & Version |  ubuntu 16.04 |
| librealsense version | 1.12.1  |
| pyrealsense version | 1.4  |

**Comment by toinsson** [comment]
Could you be more specific about the application you are running ? 
The "leak" could be in your application and not in pyrealsense for example, or simply due to the way Python is doing garbage collection.

**Comment by massimilianoC** [comment]
Hi, i have problems even with the example code: [show_cv2.py](https://github.com/toinsson/pyrealsense/blob/master/examples/show_cv2.py). 
Specifically i've misured about 190MB in 15 minutes of memory consumption running that sample code. And it's growing almost in a linear way through time, till the computer is overloaded.
I'm using that example structure for my application, so if i can optimize the example, i'm sure i'll have benefits even in my application.
Any suggestion?
Thanks for your time and for your work!!

**Comment by toinsson** [comment]
here is a snapshot of the memory usage with `show_cv2.py` for 20+ minutes under python2. It seems stable with massive fluctuation which might be explained by the way the garbage collection works.

![show_cv2_py2_30min](https://cloud.githubusercontent.com/assets/1176108/25225060/1d105fc0-25b8-11e7-8237-326fa2adeced.png)

Python3 seems to be more performant in terms of memory footprint, might be good to test out.

**Comment by massimilianoC** [comment]
Thanks. Python 3 seems to solve my problem! Thanks again
