### ISSUE TITLE
_apply_ivcam_preset Function Not Found

### ISSUE THREAD

**Issue by randyyork123** [toinsson/pyrealsense#30]
Hi there,

If I try to set an ivcam_preset like so: 
`c = pyrs.Device(ivcam_preset = 3)`

I'm getting an error:
> AttributeError: function '_apply_ivcam_preset' not found.

Librealsense is working otherwise, as are the associated examples. 
I can run pyrealsense OpenCV example and the streams are displayed.

Thanks very much!

| Camera Model | SR300 |
| Operating System & Version | Windows 10 |
| pyrealsense version | 1.4 |

**Comment by toinsson** [comment]
Hello, 
I am guessing that you are using the dev branch ?
There is a problem with rsutilwrapper indeed, I'm looking into it.

**Comment by randyyork123** [comment]
I was actually using the Windows branch. Thank you very much! 

For now, I have created a custom function that manually sets the particular options that are defined under the presets in librealsense. I know librealsense warns against this, but I think this is purely for maintaining uniformity and consistency (as it doesn't seem to be doing anything unique when the apply_ivcam_preset is called).

**Comment by toinsson** [comment]
i've made some changes which should fix the issue. Feel free to try latest on master.
