### ISSUE TITLE
DACStream format should be  rs_format.RS_FORMAT_Z16

### ISSUE THREAD

**Issue by antlai** [toinsson/pyrealsense#35]
In stream.py line 82

instead of 
self.format = rs_format.RS_FORMAT_XYZ32F

I guess it should be 
self.format = rs_format.RS_FORMAT_Z16

because is depth data...

**Comment by toinsson** [comment]
correct, if you wanna create a pull request go ahead, otherwise I'll just change that myself.

**Comment by antlai** [comment]
Go ahead and change it. One liners are probably not worth a pull request...
Thanks!
