### ISSUE TITLE
How to adjust exposure time of the Color camera of R200 sensor?

### ISSUE THREAD

**Issue by s0r2637** [toinsson/pyrealsense#36]
Hi,

I was wondering how can I create a color stream with the RGB camera's auto exposure disabled.  I know that it is possible from the Intel realsense's SDK, but does librealsense allow it.  If yes, what API calls need to be made from Pyrealsense.

| Required Info  |   |
|---|---|
| Camera Model | R200 | 
| Firmware Version |  1.0.72.10 | 
| Operating System & Version | Windows 10 64-bit  |
| librealsense version |   |
| pyrealsense version | 2.0  |

**Comment by toinsson** [comment]
You could look in `rs.h` to have an idea of the API. There is among others:
RS_OPTION_COLOR_EXPOSURE (Controls exposure time of color camera. Setting any value will disable auto exposure).
You might want to play around with its value through the method `set_device_option`.
