### ISSUE TITLE
ImportError: cannot import name rs_stream

### ISSUE THREAD

**Issue by Chris-Lelievre** [toinsson/pyrealsense#60]
| Required Info  |   |
|---|---|
| Camera Model | R200| 
| Firmware Version |   | 
| Operating System & Version | Windows 10 Education 1607 |
| librealsense version | 10.0.26.0396  |
| pyrealsense version |  2.1 |

Believe computer is set up correctly but when I try to import pyrealsense I get the following error:

Traceback (most recent call last):
  File "\\st-james.ecs.vuw.ac.nz\lelievchri\Engr 489\python\unnumbered\pyrealsense_show_cv2.py", line 7, in <module>
    import pyrealsense as pyrs
  File "C:\Python27\lib\site-packages\pyrealsense\__init__.py", line 8, in <module>
    from .core import Service
  File "C:\Python27\lib\site-packages\pyrealsense\core.py", line 15, in <module>
    from .constants import RS_API_VERSION, rs_stream, rs_option
ImportError: cannot import name rs_stream

This is weird because pyrealsense works fine on a different identical computer. Any clues?

The script I ran is your show_cv2.py example but it also does this simply entering import pyrealsense in a command prompt.

Thanks heaps

**Comment by papr** [comment]
@Chris-Lelievre Could you try running the same example using Python 3?

**Comment by Chris-Lelievre** [comment]
When I try to install pyrealsense in python 3 I get the following error and I have no idea what it means, any help appreciated!


pip install pyrealsense
Collecting pyrealsense
 Using cached pyrealsense-2.2.tar.gz
Requirement already satisfied: numpy in c:\users\lelievchri\appdata\local\programs\python\python36-32\lib\site-packages (from pyrealsense)
Requirement already satisfied: cython in c:\users\lelievchri\appdata\local\programs\python\python36-32\lib\site-packages (from pyrealsense)
Requirement already satisfied: pycparser in c:\users\lelievchri\appdata\local\programs\python\python36-32\lib\site-packages (from pyrealsense)
Requirement already satisfied: six in c:\users\lelievchri\appdata\local\programs\python\python36-32\lib\site-packages (from pyrealsense)
Installing collected packages: pyrealsense
  Running setup.py install for pyrealsense ... error
    Complete output from command c:\users\lelievchri\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;\_\_file\_\_='C:\\Users\\LELIEV~1\\AppData\\Local\\Temp\\pip-build-9ha1rv6a\\pyrealsense\\setup.py';f=getattr(tokenize, 'open', open)(\_\_file\_\_);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, \_\_file\_\_, 'exec'))" install --record C:\Users\LELIEV\~1\AppData\Local\Temp\pip-znmszvxq-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\pyrealsense
    copying pyrealsense\constants.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\core.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\extlib.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\extstruct.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\offline.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\stream.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\utils.py -> build\lib.win32-3.6\pyrealsense
    copying pyrealsense\__init__.py -> build\lib.win32-3.6\pyrealsense
    running build_ext
    building 'pyrealsense.rsutilwrapper' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\pyrealsense
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\lelievchri\appdata\local\programs\python\python36-32\lib\site-packages\numpy\core\include -I/usr/local/include/librealsense "-IC:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include" -Ic:\users\lelievchri\appdata\local\programs\python\python36-32\include -Ic:\users\lelievchri\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tppyrealsense/rsutilwrapper.cpp /Fobuild\temp.win32-3.6\Release\pyrealsense/rsutilwrapper.obj
    rsutilwrapper.cpp
    c:\users\lelievchri\appdata\local\programs\common\microsoft\visual c++ for python\9.0\vc\include\codeanalysis\sourceannotations.h(68): warning C4467: usage of ATL attributes is deprecated
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime.h(92): warning C4005: '_CRT_STRINGIZE': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(180): note: see previous definition of '_CRT_STRINGIZE'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime.h(95): warning C4005: '_CRT_WIDE': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(185): note: see previous definition of '_CRT_WIDE'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime.h(156): warning C4005: '__CRTDECL': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(650): note: see previous definition of '__CRTDECL'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime.h(293): warning C4005: '_CRT_WARNING': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtwrn.h(24): note: see previous definition of '_CRT_WARNING'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(457): error C2059: syntax error: 'constant'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(457): error C2144: syntax error: 'int' should be preceded by ';'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(457): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(457): warning C4183: '_Field_range_': missing return type; assumed to be a member function returning 'int'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(467): error C2371: '_locale_t': redefinition; different basic types
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(2047): note: see declaration of '_locale_t'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(522): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_0': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(675): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_0'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(533): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_1': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(686): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_1'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(544): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_2': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(697): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_2'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(555): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_3': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(708): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_3'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(566): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_4': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(719): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_4'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(577): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_1_1': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(730): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_1_1'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(588): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_1_2': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(741): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_1_2'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(599): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_1_3': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(752): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_1_3'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(610): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_2_0': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(763): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_2_0'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(626): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_1_ARGLIST': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(779): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_1_ARGLIST'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(642): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_2_ARGLIST': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(795): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_2_ARGLIST'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(659): warning C4005: '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_SPLITPATH': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(806): note: see previous definition of '__DEFINE_CPP_OVERLOAD_SECURE_FUNC_SPLITPATH'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(703): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_1_ARGLIST': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(848): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_1_ARGLIST'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(706): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_2_ARGLIST': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(851): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_2_ARGLIST'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(738): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_NFUNC_0_1_ARGLIST': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(882): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_NFUNC_0_1_ARGLIST'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(1785): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_1_ARGLIST_EX': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(1923): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_1_ARGLIST_EX'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(1789): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_2_ARGLIST_EX': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(1927): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_2_ARGLIST_EX'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(1823): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_NFUNC_0_1_ARGLIST_EX': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(1961): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_NFUNC_0_1_ARGLIST_EX'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(1831): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_NFUNC_0_2_ARGLIST_EX': macro redefinition
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\crtdefs.h(1969): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_NFUNC_0_2_ARGLIST_EX'
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\wchar.h(1171): error C2371: 'mbstate_t': redefinition; different basic types
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(475): note: see declaration of 'mbstate_t'
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\wchar.h(1209): error C2676: binary '==': 'const mbstate_t' does not define this operator or a conversion to a type acceptable to the predefined operator
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\time.h(281): error C2090: function returns array
    c:\users\lelievchri\appdata\local\programs\python\python36-32\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\yvals.h(122): warning C4005: '\_\_FILEW\_\_': macro redefinition
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(143): note: see previous definition of '\_\_FILEW\_\_'
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\yvals.h(123): warning C4005: '\_\_FUNCTIONW\_\_': macro redefinition
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(144): note: see previous definition of '\_\_FUNCTIONW\_\_'
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\yvals.h(821): error C2371: '_Mbstatet': redefinition; different basic types
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt.h(470): note: see declaration of '_Mbstatet'
    C:\Users\lelievchri\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\new(82): warning C4985: 'operator new[]': attributes not present on previous declaration.
    predefined C++ types (compiler internal)(37): note: see declaration of 'operator new[]'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\lelievchri\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;\_\_file\_\_='C:\\Users\\LELIEV~1\\AppData\\Local\\Temp\\pip-build-9ha1rv6a\\pyrealsense\\setup.py';f=getattr(tokenize, 'open', open)(\_\_file\_\_);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, \_\_file\_\_, 'exec'))" install --record C:\Users\LELIEV\~1\AppData\Local\Temp\pip-znmszvxq-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\LELIEV\~1\AppData\Local\Temp\pip-build-9ha1rv6a\pyrealsense\

**Comment by toinsson** [comment]
any progress? If you found the issue, please comment and close.

**Comment by Chris-Lelievre** [comment]
Have not found the issue but the project I'm working on using this is coming to a close so I'm not actively looking to fix this myself. Feel free to close the issue if you want.
Cheers
