### ISSUE TITLE
Different depth results between mac and windows

### ISSUE THREAD

**Issue by Mansterteddy** [toinsson/pyrealsense#61]
| Required Info  |   |
|---|---|
| Camera Model | R200 | 
| Firmware Version |   | 
| Operating System & Version | Mac OS X 10.12.6  |
| librealsense version |   |
| pyrealsense version |   |

Hey, thanks for providing this amazing library!
However, when I use demo program (show_depth.py) on Mac, the depth result is not as good as result from realsense SDK on Windows.
How can I solve this problem? Thanks!

**Comment by toinsson** [comment]
Hello, 
could you provide some data? 
Otherwise it might be difficult to understand what you mean by "not as good" : ) 
It would be interesting to know whether the data is the same, or the difference comes from its visualisation.

**Comment by Mansterteddy** [comment]
Hey, thanks for replying! I capture some results as follows.

For windows, I capture results with realsense SDK:
![realsense](https://user-images.githubusercontent.com/4213523/31847580-8772e78c-b651-11e7-9d8c-b2641397505f.PNG)

For mac, I capture results with your examples:
![1](https://user-images.githubusercontent.com/4213523/31847586-9654c630-b651-11e7-917b-55dca50c5452.png)
![2](https://user-images.githubusercontent.com/4213523/31847588-97f421ca-b651-11e7-991e-d1c1ae584ae9.png)

Can you tell me how to solve this issue?

**Comment by toinsson** [comment]
the difference comes from the way you plot your data. 
This is not a pyrealsense issue. You will have to look into the visualisation code.
