### ISSUE TITLE
pyrealsense installation problem on ubuntu 16.04

### ISSUE THREAD

**Issue by ljc19800331** [toinsson/pyrealsense#66]
| Required Info  |   |
|---|---|
| Camera Model | \SR300 | 
| Firmware Version |  lenovo X1 | 
| Operating System & Version | ubuntu 16.04  |
| librealsense version | latest on github  |
| pyrealsense version | latest on github  |

running install
running bdist_egg
running egg_info
writing requirements to pyrealsense.egg-info/requires.txt
writing pyrealsense.egg-info/PKG-INFO
writing top-level names to pyrealsense.egg-info/top_level.txt
writing dependency_links to pyrealsense.egg-info/dependency_links.txt
reading manifest file 'pyrealsense.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyrealsense.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'pyrealsense.rsutilwrapper' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/librealsense -I/usr/include/python2.7 -c pyrealsense/rsutilwrapper.cpp -o build/temp.linux-x86_64-2.7/pyrealsense/rsutilwrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pyrealsense/rsutilwrapper.cpp:473:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
pyrealsense/rsutilwrapper.cpp:476:16: fatal error: rs.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by toinsson** [comment]
pyrealsense is unfortunately not compatible with librealsense2, which is version you have installed by selecting the latest on librealsense github, see issue #55. There is however a binding provided by librealsense that you might be able to install with pip, pyrealsense2.
