### ISSUE TITLE
About pyrealsense.Device.pointcloud

### ISSUE THREAD

**Issue by uiossha** [toinsson/pyrealsense#7]
Hello ^^ may I ask some question
 when I use the following code:
***
pyrs.start()
dev = pyrs.Device()

dev.wait_for_frame()

array1 = dev.pointcloud
***
I got the array1
what's the structure of array1.
I am using the package from pcl to save this array to .pcd files,
but the dimension seems to be different, so I would like to ask what each elements in the array1 stands for.

**Comment by toinsson** [comment]
Array1 is a numpy array of size (480, 640, 3) and type float32, from array1.shape, array1.dtype. 
(Maybe pcl needs array of shape (X, 3) so you could reshape array1.reshape(-1,3))
