### ISSUE TITLE
 unresolved external symbol PyInit_rsutilwrapper

### ISSUE THREAD

**Issue by kilsen512** [toinsson/pyrealsense#8]
Hi,
thank you for your work. I am trying to compile this for windows 10, but I am stuck at this error.
I compiled librealsense lib with Visual Studio for Windows in 32 bit.

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:/Users/user/Projects/librealsense/bin/Win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" realsense.lib /EXPORT:PyInit_rsutilwrapper build\temp.win-amd64-3.5\Release\pyrealsense/rsutilwrapper.obj /OUT:build\lib.win-amd64-3.5\pyrealsense\rsutilwrapper.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\pyrealsense\rsutilwrapper.cp35-win_amd64.lib
LINK : error LNK2001: unresolved external symbol PyInit_rsutilwrapper
build\temp.win-amd64-3.5\Release\pyrealsense\rsutilwrapper.cp35-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120`

Do you have an idea how to fix it?

Thanks!

**Comment by toinsson** [comment]
from quick google search: 
"64-bit Python cannot be used to build 32-bit extensions. Yes, you can build
extensions for 32-bit Python on 64-bit Windows, but not with 64-bit Python." - [link](http://grokbase.com/t/python/cython-devel/148e9sy24z/cython-error-lnk2001-unresolved-external-symbol-pyinit-init)

Maybe that could be a good start to use same architecture for both lib and python.

I am currently not developing on Windows, so I might have some problem reproducing your error.
