### ISSUE TITLE
installing pyrealsense

### ISSUE THREAD

**Issue by cnaaq** [toinsson/pyrealsense#88]
| Required Info  |   |
|---|---|
| Camera Model | R200 | 
| Firmware Version | ? | 
| Operating System & Version | Windows 10  |
| librealsense version | 1.12.1  |
| pyrealsense version | cannot install  |

Hi,
I am having a miserable time(!) trying to understand how to make pyrealsense work. you mentioned in your installation tutorial that we have to install librealsense and run the examples. there is no .exe file to install it. and when I try to run the examples there is an error saying that RealSense.lib cannot be found.

**Comment by AngeloEspinoza** [comment]
Could you install it? I'm struggling with the installation as well
