### ISSUE TITLE
Install librealsense-1.12.1 and pyrealsense on Raspberry Pi4 for F200

### ISSUE THREAD

**Issue by congvm-cs** [toinsson/pyrealsense#91]
| Required Info  |   |
|---|---|
| Camera Model | R200, F200 or SR300 | 
| Firmware Version |   | 
| Operating System & Version | Raspbian  |
| librealsense version |  1.12.1 |
| pyrealsense version |  2.2  |

I intend to buy a Raspberry Pi 4 to integrate with my Realsense F200 but I am not sure they will work. Have you ever use these combination on you own project? Please give me a suggestion.

**Comment by toinsson** [comment]
This has not been tested. Any luck?
